from environ import (POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_HOST,
                     POSTGRES_PORT, POSTGRES_DB)


DATABASE_URL = f'postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}' \
               f'@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}'
